#
# Q) What is Network_cli?
# Ans) Synopsis. This connection plugin provides a connection to remote devices over the SSH and implements a CLI shell.
# This connection plugin is typically used by network devices for sending and receiving CLi commands to network devices.
# https://docs.ansible.com/ansible/latest/network/getting_started/network_differences.html
# what is Persistent?
# __determined to continue doing something even though people say that you are wrong or that you cannot do it
# __lasting for a long time or happening often

---
- name: Running with multiple command for Cisco
  hosts: Routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Lets check out with show ver & show arp
      ios_command:
        commands:
          - show arp
          - show version

      register: commandOut

    -   debug: var=commandOut.stdout_lines
...

# Output:
# 
#