###
# 4.0 Saving output to a file !!!
#Q) What is Ansible Jinja2 template?
#Ans) Jinja2 templates are simple template files that store variables that can change from time to time.
# When Playbooks are executed, these variables get replaced by actual values defined in Ansible Playbooks.
# This way, templating offers an efficient and flexible solution to create or alter configuration file with ease.
#Lets code
---
- name: Pre & Post Preparartion to the folder
  hosts: l2sw
  gather_facts: false
  connection: network_cli

  tasts:
    - name: Pre Captured for multiple command
      ios_command:
        commands:
          - show running
          - show int status
          - show ip int brief

      register: commandOut

    - name: Save pre capture output into a folder
      copy:
        content: "{{commandOut.stdout[0]}}"
        dest: "~/Backup/{{inventory_hostname}}.txt"
...

##
#Output:
#