#
# 1.0 Very basic play: PLAY & PLAY RECAP
# Note: "#" this is use for comment 
# shortcut to comment in & out "Ctrl+/"
#

---
- name: This very first one
  hosts: Hosts Routers
  gather_facts: false

...

# command:
# ansible-playbook ansiblecode.yaml -u ashu -k
#
# Output:
# student@linux1  $ansible-playbook ansiblecode.yaml -u ashu -k
# SSH password: 
#
# PLAY [This very first one] *****************************************************
#
# PLAY RECAP *********************************************************************
#
# student@linux1  $
#