#
# 1.0 Very basic play: PLAY & PLAY RECAP
# Note: "#" this is use for comment 
# shortcut to comment in & out "Ctrl+/"
#

---
- name: This very first one
  hosts: Routers
  gather_facts: false

  tasks:
    - name: Get basic command ARP using raw modules
      raw: show ip arp

      register: arpOut

    - name: Print & Debug the output
      debug: var=arpOut
...

# command:
# ansible-playbook ansiblecode.yaml -u ashu -k
#
# Output:
# Its print all default output 1) stderr 2)stderr_lines 3)stdout 4)stdout_lines
#