###
##
# 4.1 Saving Output to a folder for multiple command !!!
# Understand ARRAY concept "[0], [1], [2], [0][1]" & nullify the []

---
- name: Pre & Post Preparartion to the folder
  hosts: l2sw
  gather_facts: false
  connection: network_cli

  tasts:
    - name: Pre Captured for multiple command
      ios_command:
        commands:
          - show running
          - show int status
          - show ip int brief

      register: commandOut

    - name: Save pre capture output into a folder
      copy:
        content: "{{commandOut.stdout[1]}}"
        dest: "~/Backup/{{inventory_hostname}}.txt"
...



#