#
#Q) What is connection local in Ansible?
#Ans) It is to execute the tasks locally on the same host (i.e., the controller) where the playbook is run.
# From the documentation, It may be useful to use a playbook locally, rather than by connecting over SSH

---
- name: Running with multiple command for Cisco
  hosts: Routers
  gather_facts: false
  connection: local

  tasks:
    - name: Lets check out with show ver & show arp
      ios_command:
        commands:
          - show arp
          - show version

      register: commandOut

    -   debug: var=commandOut.stdout_lines
...

# Output:
# 
#